version: '3.8'

services:
  fastify:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres_user
      DB_PASSWORD: postgres_password
      DB_NAME: postgres_db
    depends_on:
      - postgres
    networks:
      - fastify_network

  postgres:
    image: postgres:15
    container_name: postgres_container1
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fastify_network

volumes:
  db_data:

networks:
  fastify_network:
    driver: bridge
